apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-gateway/ingress.yaml
  - flux-test.yaml
  - container-registry-dragonfly/dragonfly.yaml
  - feature-flagging-openfeature/openfeature.yaml
  - security-cert-manager/cert-manager.yaml
  - feature-flagging-openfeature/flags.yaml
  - application-demo/demo-app.yaml
